---
# tasks file for InServerCommon
# change sudo
- name: Check whether /etc/sudoers enable sudo"
  command: grep -q "#\s*%wheel\s\+ALL=(ALL)" /etc/sudoers
  register: sudoNex
  always_run: True
  ignore_errors: True
  changed_when: False

- name: change sudo
  script: change_sudo.sh
  when: sudoNex.rc != 0

- name: hostname should match inventory name
  hostname: name={{ inventory_hostname }}

- name: Creates workdir
  file: path={{work_dir}} state=directory

- name: add authorized_key for user root
  authorized_key: user=root key="{{ lookup('file', 'roles/InServerCommon/files/id_rsa.pub') }}"

- name: replace hosts eth0 name
  lineinfile: "dest=/etc/hosts state=absent regexp='^{{ansible_default_ipv4.address}}'"

- name: add all host to /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp='.*{{ item }}$'
    line="{{ hostvars[item]['ansible_ssh_host']}} {{item}}" state=present
  with_items: "{{ groups['all'] }}"
  when: enable_hosts

- name: replace hosts lo name
  lineinfile: "dest=/etc/hosts state=present regexp='^127.0.0.1' line='127.0.0.1 {{ inventory_hostname }}'"

- name: remove hosts lo name
  lineinfile: "dest=/etc/hosts state=absent regexp='^127.0.0.1'"

- name: add localhost name
  lineinfile: "dest=/etc/hosts state=present line='127.0.0.1 localhost'"

- name: Copy repo for CentOSBase
  copy: src=files/CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo force=yes

- name: Install Monitor
  include: monitor.yml
  when: enable_monitor
