---

- name: Create  app directory
  file: path={{ app_dir }}  state=directory

- name: Download filebeat package
  get_url:  url={{ filebeat_url }}/{{ filebeat_rpm }}   dest={{ app_dir }}/{{ filebeat_rpm }}

- name: Inastall filebeat
  shell:  chdir={{ app_dir }} yum install -y {{ filebeat_rpm }}

- name: Copy  filebeat  config
  template:  src=templates/conf.d/filebeat.yml.j2   dest=/etc/filebeat/filebeat.yml

- name: Started filebeat  service
  service:  name=filebeat  state=started enabled=yes 
