---
- name: Import logsstash key
  shell:  rpm --import {{ key_url }}

- name: Copy logstash repo
  copy: src=files/logstash.repo dest=/etc/yum.repos.d/logstash.repo

- name: Install logstash
  yum:  name=logstash state=present

- name: Copy  logstash  config
  template: src=templates/conf.d/logstash.yml.j2 dest=/etc/logstash/logstash.yml

- name: Create geoip directory
  file: path={{ geoip_dir }}  state=directory

- name: Download  geoipCity_name
  get_url:  url={{ geoipCity_url  }}/{{geoipCity_name}}   dest={{ geoip_dir }}

- name: Download  geoIPASNum
  get_url:  url={{geoIPASNum_url}}/{{ geoIPASNum }}   dest={{ geoip_dir }}

- name: gunzip geoip  database
  shell:  chdir={{ geoip_dir }}   gunzip  *.dat.gz

- name: Copy cowrie config
  template: src=templates/conf.d/cowrie.conf.j2 dest=/etc/logstash/conf.d/cowrie.conf

- name: Started logstash service
  service:  name=logstash state=Started enabled=yes 
