---
- name: Create hadoop_data_dir directory
  file: path={{ hadoop_data_dir }}  state=directory
- name: Create  app_dir directory
  file: path={{ app_dir }} state=directory

- name: Download  hadoop binary package
  get_url:  url={{ get_hadoop_url }}/{{ hadoop_name }}.tar.gz dest={{ app_dir }}

- name: Tar hadoop binary package
  shell:  chdir={{ app_dir }}  tar xvf {{ hadoop_name }}.tar.gz
- name: Create  hadoop logs directory
  shell:  chdir={{ app_dir }}/{{ hadoop_name }}  mkdir logs

- name: Copy  core-site configure
  template: src=templates/conf/core-site.xml.j2 dest={{ hadoop_conf_dir }}/core-site.xml
- name: Copy  hdfs-site configure
  template: src=templates/conf/hdfs-site.xml.j2 dest={{ hadoop_conf_dir }}/hdfs-site.xml
- name: Copy  yarn-site configure
  template: src=templates/conf/yarn-site.xml.j2 dest={{ hadoop_conf_dir }}/yarn-site.xml
- name: Copy mapred-site configure
  template: src=templates/conf/mapred-site.xml.j2 dest={{ hadoop_conf_dir }}/mapred-site.xml

- name: Copy  hadoop development configure
  template: src=templates/hadoop.sh.j2  dest=/etc/profile.d/hadoop.sh
- name: Source  hadoop development
  shell:  source /etc/profile.d/hadoop.sh

- name: Copy  hadoop-env configure
  template: src=templates/hadoop-env.sh.j2  dest={{ hadoop_conf_dir }}/hadoop-env.sh

- name: Format HDFS file system
  shell:  hdfs namenode -format

- name: Started HDFS Cluster
  shell:  start-dfs.sh
- name: Started YARN Cluster
  shell:  start-yarn.sh

- name: Create  zookeeper_dir directory
  file: path={{ zookeeper_dir }}  state=directory
- name: Download  hbase binary package
  get_url:  url={{ get_hbase_url }}/{{ hbase_name }}-bin.tar.gz dest={{ app_dir }}
- name: Tar hbase binary package
  shell:  chdir={{ app_dir }} tar xvf {{ hbase_name }}-bin.tar.gz

- name: Create hbase logs directory
  shell:  chdir={{ app_dir }}/{{ hbase_name }} mkdir logs
- name: Create  hbase_root directory
  shell:  hadoop fs -mkdir /hbase

- name: Copy  hbase-site configure
  template: src=templates/hbase/hbase-site.xml.j2 dest={{app_dir}}/{{hbase_name}}/conf/hbase-site.xml
- name: Copy  hbase-env configure
  template: src=templates/hbase-env.sh.j2 dest={{app_dir}}/{{hbase_name}}/conf/hbase-env.sh
- name: Copy  hbase development configure
  template: src=templates/hbase.sh.j2 dest=/etc/profile.d/hbase.sh
- name: Source hbase development configure
  shell:  source /etc/profile.d/hbase.sh

- name: Started hbase service
  shell:  start-hbase.sh
