---
- name: Create app direcoty
  file: path={{ app_data }}  state=direcoty

- name: Install python tools
  yum: name=python-setuptools state=present

- name: Easy install pip
  shell: easy_install pip

- name: Pip install tornado
  shell: pip install tornado

- name: Pip install redis
  shell: pip install redis

- name: Pip install python-dateutil
  shell: pip install python-dateutil

- name: download redis-live package
  get_url: url={{ redis_live_url }}/{{ redis_live_pak }}.zip  dest={{ app_data }}

- name: unzip redis-live package
  shell: chdir={{ app_data }} unzip {{ redis_live_pak }}.zip

- name: Rename redis-live package
  shell: chdir={{ app_data }}  mv {{ redis_live_pak }}  RedisLive

- name: Copy redis-live config
  template: src=templates/conf.d/redis-live.conf.j2 dest={{ redis_live_conf }}/redis-live.conf

- name: Started redis monitor
  shell: chdir={{ redis_live_conf }}  nohup ./redis-monitor.py --duration 300 &

- name: Started redis live
  shell: chdir={{ redis_live_conf }}  nohup ./redis-live.py &
