---
- name: install dev tools
  shell: "yum groupinstall 'development tools'  --skip-broken"
  register: installed
  until: installed|success
  retries: 5
  delay: 30

- name: make sure prepackage installed
  yum: name={{item}} state=latest
  with_items:
    - libevent

- name: Create fastdfs working directory
  file: path="{{ fast_workdir }}" state=directory

- name: Create fastdfs base directory
  file: path="{{ fast_basedir }}" state=directory

- name: install fastdfs prepackage
  include: package_install.yml

- name: config storage
  include: storage_conf.yml
  when: fast_store

- name: config tracker
  include: tracker_conf.yml
  when: not fast_store

- name: install nginx for storage
  include: store_nginx_install.yml
  when: fast_store

- name: config nginx for storage
  include: store_nginx_conf.yml
  when: fast_store
