---
# install fastdfs storage
- name: Create storage_base_path directory
  file: path="{{ fast_store_base_path }}" state=directory

- name: Create storage_store_path directory
  file: path="{{ fast_store_path0 }}" state=directory

- name: Download libfastcommon package
  get_url: url="{{ fast_libfastcommon_url }}"   dest={{ fast_workdir }}

- name: extract libfastcommon package
  unarchive: src="{{ fast_workdir }}/{{ fast_libfastcommon_package }}.tar.gz" dest={{ fast_workdir }} copy=no

- name: Make libfastcommon package
  shell: chdir="{{ fast_workdir }}/{{ fast_libfastcommon_package }}" ./make.sh

- name: Make install libfastcommon package
  shell: chdir="{{ fast_workdir }}/{{ fast_libfastcommon_package }}" ./make.sh install

- name: Download fastdfs package
  get_url: url="{{ fast_src_url }}"  dest={{ fast_workdir }}

- name: extract fastdfs package
  unarchive: src="{{ fast_workdir }}/{{ fast_package }}.tar.gz" dest={{ fast_workdir }} copy=no

- name: Make fastdfs package
  shell: "cd {{ fast_workdir }}/fastdfs-* && ./make.sh"

- name: Make install fastdfs package
  shell: "cd {{ fast_workdir }}/fastdfs-* && ./make.sh install"
