---
- name: Add group "cowrie"
  group: name=cowrie
- name: Add user "cowrie"
  user: name=cowrie group=cowrie createhome=no
  become: True
  become_method: sudo

- name: Create cowrie directory
  file: path={{ cowrie_dir }}  state=directory

- name: Install python devel
  yum: name={{ item }}  state=present
  with_items:
    - git
    - python-crypto
    - python-gmpy2
    - python2-pip
- name: Install virtualenv
  shell: pip install virtualenv

- name: Download cowrie package
  shell: chdir={{ cowrie_dir }}  git clone  {{ cowrie_url }}
- name: virtualenv cowrie-env
  shell: chdir={{ cowrie_dir }}/cowrie  virtualenv cowrie-env

- name: Source cowrie-env
  shell:  chdir={{ cowrie_dir }}/cowrie source  cowrie-env/bin/activate

- name:   Insatall requirements
  shell:  chdir={{ cowrie_dir }}/cowrie  pip install -r requirements.txt

- name: Change ownership of cowrie
  file: path={{ cowrie_dir}}  owner=cowrie group=cowrie state=directory recurse=yes

- name: Copy cowrie Configure
  template: src=templates/conf.d/cowrie.cfg.j2  dest={{ cowrie_dir }}/cowrie/cowrie.cfg

- name: Started cowrie service
  shell:  su cowrie  chdir={{ cowrie_dir }}/cowrie/bin ./cowrie start

#iptables -t nat -I PREROUTING 1 -p tcp  --dport 22 -j REDIRECT --to-port 60000
