---
- name: fast store start
  command: "{{ fast_store_bin }}  {{ fast_store_conf_path }} start"

- name: fast store stop
  command: "{{ fast_store_bin }}  {{ fast_store_conf_path }} stop"

- name: fast store restart
  command: "{{ fast_store_bin }}  {{ fast_store_conf_path }} restart"

- name: fast tracker start
  command: "{{ fast_tracker_bin }}  {{ fast_tracker_conf_path }} start"

- name: fast tracker stop
  command: "{{ fast_tracker_bin }}  {{ fast_tracker_conf_path }} stop"

- name: fast tracker restart
  command: "{{ fast_tracker_bin }}  {{ fast_tracker_conf_path }} restart"
