# install gcc gcc-c++ unzip
- name: install gcc
  yum: name=gcc state=present
- name: install gcc-c++
  yum: name=gcc-c++ state=present
- name: install unzip
  yum: name=unzip state=present
- name: install autoconf
  yum: name=autoconf state=present

# mkdir codis_config_dir codis_path codis_data
- name: mkdir codis_configure_dir
  file: dest={{ codis_configure_dir }} state=directory mode=775
- name: mkdir codis_path
  file: dest={{ codis_path }} state=directory mode=775
- name: mkdir codis_data
  file: dest={{ codis_data }} state=directory mode=775
- name: mkdir codis_log
  file: dest={{ codis_log }} state=directory mode=775

# unarchive codis
- name: unarchive codis-release3.2.zip
  unarchive: src=codis-release3.2.zip dest={{ codis_configure_dir }}/
- name: make link file codis for codis-release3.2
  file: src={{ codis_configure_dir }}/codis-release3.2 dest={{ codis_configure_dir }}/codis state=link
- name: make codis
  shell: cd {{ codis_configure_dir }}/codis/ && make MALLOC=libc
- name: copy codis/bin to codis_path/
  shell: cp -a {{ codis_configure_dir }}/codis/bin {{ codis_path }}/
#  copy: src={{ codis_configure_dir }}/codis/bin dest={{ codis_path }}/ remote_src=true directory_mode=true
- name: copy codis.sh for PATH
  template: src=codis.sh.j2 dest=/etc/profile.d/codis.sh mode=644
