---
# install elasticsearch
- name: Create elasticsearch app directory
  file: path={{ es_workdir }} state=directory
- name: create elasticsearch user
  user: name=elasticsearch
  
- name: download rpm
  get_url: url="{{ es_download_url }}" dest={{ es_workdir }}
  register: dl_result
  until: "'OK' in dl_result.msg"
  retries: 50
  delay: 10

- name: install es
  yum:
    name: "{{ es_workdir }}/{{ es_rpm_file }}"
    state: present

- name: Creates data dir
  file: path={{es_data_dir}} state=directory owner=elasticsearch group=elasticsearch

- name: Creates log dir
  file: path={{es_log_dir}} state=directory owner=elasticsearch group=elasticsearch

- name: enable service
  service: name=elasticsearch enabled=yes
